### ISSUE TITLE
Cannot import multiple files with the same name

### ISSUE THREAD

**Issue by markod0925** [Assets-Manager/AssetsManager#1]
Hi, 

I have tried to copy-paste a directory with png assets in the assetsdb dir. The software starts properly to import the assets, but at the end I see that the files with the same names (but in different directories) have not been copied. Only one file per name has been copied.

Example of dir:
RED\001.PNG
RED\002.PNG
GREEN\001.PNG
 etc.

If I try to import this I will find only one 001.PNG.

Another question, there is not an Import button to import a whole directory?

Cheers,

Marco

**Comment by tostc** [comment]
Hey,

I will look into this. To your question, normally you can import directories, or files by dragging and dropping them on the window.

**Comment by markod0925** [comment]
Thank you, it is a very nice tool and I really like to use it!

Il sab 10 feb 2024, 12:07 tostc ***@***.***> ha scritto:

**Comment by markod0925** [comment]
Hi,
I saw that you have fixed this issue. Thank you! 
Do you plan to release the new build on itch.io?

**Comment by tostc** [comment]
Hey,

the bug isn't fixed to 100%. But I've implemented already everything to finally fix it. After that and testing I will release a new version to Itch. But I don't currently have a release date.  Please have a little patience.  This is just a little hobby project that I do in my free time.

**Comment by markod0925** [comment]
Don't worry, when it's ready I will download it. In the meantime I am using it for other no-single-name assets.

**Comment by tostc** [comment]
Hey,

just to let you know, the new version is on itch.

**Comment by markod0925** [comment]
Thank you!!

**Comment by tostc** [comment]
Here you go.
